### ISSUE TITLE
大佬脚本很牛逼，但是自动打玉模式和大号模式自动切图后无法正常打怪

### ISSUE THREAD

**Issue by Dhy827** [pyDraco9/ChuanQiBazhuScript#1]
自动切图后打怪都是打一下就跑，大佬有空了帮忙看一下
![微信截图_20220520142318](https://user-images.githubusercontent.com/55142573/169466223-5550e16d-1850-401d-bceb-e76dc20195b6.png)

**Comment by pyDraco9** [comment]
切换后开关一次自动挂机，已经快一年了忘记原因了，好像是有些变量直接切换会有一些遗留问题……

**Comment by Dhy827** [comment]
沙雕游戏不玩也罢退坑

**Comment by yuqi199211251** [comment]
大佬是不是少上传一个文件，我这提示emIns未定义，这是个内置参数么？

**Comment by pyDraco9** [comment]
> 大佬是不是少上传一个文件，我这提示emIns未定义，这是个内置参数么？

emIns是游戏定义的，可能游戏修改了全局变量，可自行通过搜索`.firstPlayer`查找游戏把变量修改成了什么。

**Comment by yuqi199211251** [comment]
大佬，
       恕我愚钝，怎么查看游戏的方法属性，例如您给我发的.firstPlayer方法，怎么调用的？或者说您是怎么知道有.firstPlayer方法的？我看游戏是canvas画布

发件人: Draco9 ***@***.***>
发送时间: 2022年9月11日 10:04
收件人: pyDraco9/ChuanQiBazhuScript ***@***.***>
抄送: Yu Qi 于齐 ***@***.***>; Comment ***@***.***>
主题: Re: [pyDraco9/ChuanQiBazhuScript] 大佬脚本很牛逼，但是自动打玉模式和大号模式自动切图后无法正常打怪 (Issue #1)

CAUTION: This email originated from outside the organization. Do not click or open attachment/link unless you recognize the sender and know the content is safe

大佬是不是少上传一个文件，我这提示emIns未定义，这是个内置参数么？

emIns是游戏定义的，可能游戏修改了全局变量，可自行通过搜索.firstPlayer查找游戏把变量修改成了什么。

**Comment by pyDraco9** [comment]
> 大佬， 恕我愚钝，怎么查看游戏的方法属性，例如您给我发的.firstPlayer方法，怎么调用的？或者说您是怎么知道有.firstPlayer方法的？我看游戏是canvas画布 

游戏有自带的Debug输出，在控制台中可以看到，在控制台输出的位置直接查看输出来源的.js文件可以找到游戏的主要封包处理/逻辑处理，由于游戏没有闭包处理所有函数和代码，部分变量/protocol可以直接调用。

出于安全考虑，恐怕进一步对游戏的逆向工程我不能再教了，H5页游虽然都通过canvas画布绘制内容，但通常通过封包可以定位到最初发包的位置，然后向上查找调用来源。
大部分游戏厂商的闭包做的都比较好，只有少数像本游戏才可以直接调用。
闭包做的比较好的游戏，可以通过逆向封包自己做纯封包交互，完成脱机。
